version: '3'

services:

  portainer:
    image: portainer/portainer
    ports:
      - "9000:9000"
    #credentials: admin / OVl54Zzd
    command:
      -H unix:///var/run/docker.sock
      --admin-password '$$2y$$05$$lq1JCom9zhZEgcnOD2w4jekHTCz0jV.ixuHzgIqrYZesFq.o7cN0q'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - $HOME/com.gether.toolbox/certs:/certs

  postgres:
    container_name: "postgres"
    image: "postgres:alpine"
    volumes:
      - ../docker/postgres:/docker-entrypoint-initdb.d
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_MULTIPLE_DATABASES=${USERS_DB_NAME},${FINANCIAL_TRANSACTIONS_DB_NAME},${FINANCIAL_BALANCE_DB_NAME}
    ports:
      - 5432:5432

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq
    #      volumes:
    #        - ./.docker/rabbitmq/etc/:/etc/rabbitmq/
    #        - ./.docker/rabbitmq/data/:/var/lib/rabbitmq/
    #        - ./.docker/rabbitmq/logs/:/var/log/rabbitmq/
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
    ports:
      - 5672:5672
      - 15672:15672

#volumes:
#
#  postgres-volume:
#    driver_opts:
#      type: none
#      o: bind
#      device: $HOME/com.gether/postgres