version: '3'

services:

  gateway:
    image: com.modus.create/gateway
    ports:
      - "8010:8010"
    depends_on:
      - portainer
      - postgres
      - rabbitmq

  users:
    image: com.modus.create/users
    ports:
      - "8011:8011"
    depends_on:
      - portainer
      - postgres
      - rabbitmq

  financial-transactions:
    image: com.modus.create/financial-transactions
    ports:
      - "8012:8012"
    depends_on:
      - portainer
      - postgres
      - rabbitmq

  financial-balance:
    image: com.modus.create/financial-balance
    ports:
      - "8013:8013"
    depends_on:
      - portainer
      - postgres
      - rabbitmq